#!/usr/bin/env python
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# QEcalc              by DANSE Inelastic group
#                     Brent Fultz
#                     California Institute of Technology
#                     (C) 2009  All Rights Reserved
#
# File coded by:      Nikolay Markovskiy
#
# See AUTHORS.txt for a list of people who contributed.
# See LICENSE.txt for license information.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
import string
from qe_io_dict import *
import numpy
from baseoutput import BaseOutput

class Output(BaseOutput):

    def __init__(self):
        BaseOutput.__init__(self)
        self.parsers = {
                    'single phonon' : self.getSinglePhonon
                }

    def getSinglePhonon(self, setting):
        """Obtain a list of phonon modes from output generated by dynmat.x"""
        dynmatOut = read_file(setting.dynmatOutput)
        keyStart = find_key_from_marker_string(dynmatOut, '#', 'mode')
        modeNum = 1
        key = keyStart + 1
        words = string.split(dynmatOut[key])
        modes = []
        while words[0]	 == str(modeNum):
            modes.append( float(words[1]))
            key = key + 1
            modeNum = modeNum + 1
            words = string.split(dynmatOut[key])
        return [(modes, 'cm-1')]
    

if __name__ == "__main__":
    print "Hello World";

__author__="Nikolay Markovskiy"
__date__ ="$Oct 18, 2009 7:28:06 PM$"